### ISSUE TITLE
[BUG]: Removed module is still being referenced 

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#216]
### Conda environment check

- [X] I have tried using the `osemosys-global` conda environment.

### Current Behavior

The visualization script still references an old powerplant file. We need to change this import 

https://github.com/OSeMOSYS/osemosys_global/blob/2a3e961382604c492d28acd43150bd8005c84c50/workflow/scripts/osemosys_global/visualisation/utils.py#L11

**Comment by maartenbrinkerink** [comment]
@trevorb1 The 'format_transmission_name' function is non-existing anymore. This function existed to format transmission data coming from the PLEXOS-World datasets (e.g. the from/to columns) but since transmission data is now being pulled from the Global Transmission Data directly (which is in native OG formatting) it is outdated. I forgot that the visualization scripts pull PW data so haven't updated that. Will turn it into a new issue.

**Comment by maartenbrinkerink** [comment]
Connections to the legacy transmission input files are now removed.
