### ISSUE TITLE
Set RES resource limits

### ISSUE THREAD

**Issue by maartenbrinkerink** [OSeMOSYS/osemosys_global#97]

**Comment by maartenbrinkerink** [comment]
@trevorb1 I've added a temp script ('TEMP_RESlimit.py') that pulls the RES limit data including initial conversion. Just remove the file once you're done. Notes;

- I didn't want to break the existing scripts, so please just copy the relevant part of the script and integrate it in OPG_powerplant_data.py when converting the data into the relevant OSeMOSYS variable.
- The values right now are in GW, if MW is the correct unit please remove the / 1000 in the script.
- I haven't added the 'YEAR' column (should be same values for all years) since this should probably be read from the config file?

Let me know if anything is unclear. I'll add the data descriptions/sources in the doc file next week.

Cheers

**Comment by trevorb1** [comment]
Hey @maartenbrinkerink ! 

Thanks for the updates! I have added in the last portion to convert the capacity limits to match otoole/osemosys formatting. One question though, there seems to be a mismatch between the the residual capacity and total annual max capacity limits. 

Specifically, for PWRHYDINDSO01, the residual capacity in 2015 is 12.7563GW but the annual max capacity limit is 3.8GW. So OSeMOSYS throws an error during the model creation stage. I checked to make sure everything was getting converted to GW, but other then that, off the top of my head I don't know where the error could be coming from. Just wanted to check if you had any thoughts before I investigate the error a little closer, since your familiar with the PLEXOS datasets? 

My rough work is just in a branch called `max-capacity` if you are wanting to look. I have the changes in a separate script right now called `OPG_max_capacity.py`. 

Thanks! Happy to jump on a call whenever as well to discuss the error!

**Comment by maartenbrinkerink** [comment]
@trevorb1 I hadn't considered this yet, but the values are for NEW capacity only. E.g. the constraints in our PLEXOS model work as such that a 'New Capacity Built' constraint is set that allows the model to invest in currently untapped locations for new renewables. So if you want to have a total constraint that caps max capacity based on existing+new locations you'd have to add the existing capacity (so e.g. residual capacity in year 0 for PWRHYDINDSO00) with the max new capacity. Let me know if this works if not i'll have a look later this week.

**Comment by trevorb1** [comment]
@maartenbrinkerink Thanks! I have updated the script so the `TotalAnnualMaxCapacity` value in OSeMOSYS is generated using the PLEXOS values you provided plus the residual capacity. 

For the residual capacity, I was a little uncertain if it should be the capacity in 2015, or if we should be adjusting for the start year that the user inputs? I think hard coding in to just use the 2015 value seems better since we wont have to account for powerplants becoming decommissioned that way? (and thats whats currently implemented)

Also, I think there are a few powerplants that don't have capacity limits from the PLEXOS data set. Specifically, the ones listed below. In these cases, I have no max capacity limit being set. Not sure if I should just be inputting a standard limit in these cases? (ie. like double the current capacity or something?) 

```
WARNING: No max cap set for PWRWONATAXX01
WARNING: No max cap set for PWRSPVCPVXX01
WARNING: No max cap set for PWRWONCPVXX01
WARNING: No max cap set for PWRHYDFJIXX01
WARNING: No max cap set for PWRWONFJIXX01
WARNING: No max cap set for PWRHYDGUFXX01
WARNING: No max cap set for PWRSPVGUFXX01
WARNING: No max cap set for PWRHYDKOSXX01
WARNING: No max cap set for PWRHYDMUSXX01
WARNING: No max cap set for PWRSPVMUSXX01
```

**Comment by maartenbrinkerink** [comment]
@trevorb1 Great stuff! Regarding your questions;

- I'd say 2015 as base year because I think it is fair to assume that any existing location can also be used again in the future even after decommissioning of a current plant. So hard coding works for me, just be certain that you make a note somewhere that if we change to an e.g. 2020 PLEXOS-World model as base dataset the base year for this gets adjusted as well.
- Regarding the absence of certain capacity limits, for HYD this means that no economic locations exist following the used study (globally about 60.000 identified new locations for HYD) so the constraint should be 0. For wind/solar this likely means that the above countries weren't included in the used datasets. Note that in general wind/solar potentials are a multifold of what a country would need to meet its domestic demand, so with that in mind i'd say to put in a high number as constraint that will be never be met since the countries with missing values are all relatively small (e.g. a 20 GW limit or so).

**Comment by trevorb1** [comment]
Perfect, thanks @maartenbrinkerink ! I made those changes and everything is behaving as expected. I will merge in the updates, close this issue, and update the documentation.
